### ISSUE TITLE
Authentication without req.session

### ISSUE THREAD

**Issue by eric-burel** [FusionAuth/fusionauth-example-react#6]
Hi, I am implementing authentication on a Next.js app using FusionAuth.

Looking at this code:
https://github.com/FusionAuth/fusionauth-example-react/blob/master/server/routes/oauth-callback.js

I see that you store the access_token within req.session. I am not fond of this kind of stateful setup server-side, I'd rather store tokens in the browser's cookies, or localStorage for persistence from session to session.

- As far as I understand, if I want to pass more data to the frontend, it will be through the query params of the redirect URI
- Do you think it would be safe to pass the access token in the redirect URI? The answers seems to be no, since passing sensitive values within an URL is not the best deal (it will persist in the history, can be seen by shoulder surfing etc., [see this ressource](https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url))
- Instead, I could pass the "code" to the frontend instead of the token, so it then requires an access_token. It will mean another request after the redirect to get the token in exchange of the code. It seems the best approach but kinda circumvented, do I miss something?

I've hesitated to post this as SO question, let me know if this is not appropriate. I know this sounds like beginner questions, but I struggle to find any relevant and understandable source. It seems to be "obvious", and the role of redirect_uri is often brushed of, yet I don't think it is.

Example of docs I find in the wild:
- https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uri-validation/ They go as far as explaining exchanging code for a token... but then nothing on how you pass it to your frontend app.
- https://stackoverflow.com/questions/63204591/how-can-i-send-jwt-token-to-client-after-oauth-autherization: seems to advise to store the token on the server... this seems kind of weird to me, it makes the API stateful then?
- https://stackoverflow.com/questions/35510392/where-should-the-access-token-be-placed-at-successful-login seems to consider access_token in the redirection URL

**Comment by voidmain** [comment]
The general rules for OAuth are:

* Never include tokens (access, id, refresh) in URLs
* Never store tokens in local storage
* Never transfer tokens over unencrypted channels

In your case, if you want to get rid of server-side sessions, you should use http-only secure cookies and Authorization Code Grant. It would work like this:

1. User clicks login button and goes to FusionAuth via OAuth (using Authorization Code Grant with PCKE)
2. User logs in and FusionAuth redirects back to your app via the `redirect_uri`
3. Your app's backend handles the redirect and uses the `code` from the URL to complete the Authorization Grant by calling the token endpoint to get an access token and refresh token.
4. Your app's backend responds to this request with another redirect back to your Next.js app PLUS two http-only secure cookies. One that stores the access token (JWT) and one that stores the refresh token. Ensure that these cookies are at the correct domain so that your Next.js app will send them across the wire with every API call.
5. The browser requests your Next.js app and opens it up.
6. Your Next.js app makes an API call to your app backend and it sends across the two cookies (yay!)

Step 4 is the key to this working and then you should have everything you need during an API call to authorize the request.

Here is a guide I wrote that outlines this process:

https://fusionauth.io/learn/expert-advice/authentication/spa/oauth-authorization-code-grant-jwts-refresh-tokens-cookies

**Comment by eric-burel** [comment]
Great explanation, I think the missing piece for me is this: https://stackoverflow.com/questions/37744629/send-a-set-cookie-header-to-a-redirect-url-in-node-js
So that I don't need to have the token in the URL (+ it simplifies my frontend code since I don't manually set the cookie too). I think it would work as I expect in this scenaerio.
Thanks a lot!
